<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\DDDProject.Application\DDDProject.Application.csproj" />
      <ProjectReference Include="..\DDDProject.Domain\DDDProject.Domain.csproj" />
      <ProjectReference Include="..\DDDProject.Persistence\DDDProject.Persistence.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Hangfire.MemoryStorage" Version="1.8.1.1" />
    </ItemGroup>

</Project>
